DATALOADER:
  NUM_WORKERS: 8

DATASET:
  DIR: data
  TEST: ()
  TRAIN: ()

INPUT:
  MAX_SCALE_TRAIN: 1.2
  MIN_SCALE_TRAIN: 0.5
  PIXEL_MEAN:
    - 0.5071
    - 0.4867
    - 0.4408
  PIXEL_STD:
    - 0.2675
    - 0.2565
    - 0.2761
  PROB: 0.5
  SIZE_TEST: 32
  SIZE_TRAIN: 32

MODEL:
  DEVICE: cuda
  NUM_CLASSES: 100

OUTPUT_DIR: ""

SOLVER:
  BASE_LR: 0.001
  BIAS_LR_FACTOR: 2
  CHECKPOINT_PERIOD: 10
  GAMMA: 0.1
  IMS_PER_BATCH: 16
  LOG_PERIOD: 100
  MAX_EPOCHS: 50
  MOMENTUM: 0.9
  OPTIMIZER_NAME: SGD
  STEPS: (30000,)
  WARMUP_FACTOR: 0.3333333333333333
  WARMUP_ITERS: 500
  WARMUP_METHOD: linear
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0

TEST:
  IMS_PER_BATCH: 8
  WEIGHT: null
